theme: minima
title: Agpollackberti-code
author: agpollackberti-code
email: agpollackberti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Humans learn best through practice, so here is a human practicing code!  

# social links
twitter_username: AmberBerti # DO NOT include the @ character, or else the build will fail!
github_username:  agpollackberti-code # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
